//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.19 at 12:54:00 AM MSK 
//


package ru.datana.steel.parser.xml.pojo;

import lombok.ToString;

import javax.xml.bind.annotation.*;


@XmlRootElement(namespace = "", name = "root")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rootType", propOrder = {
        "controllers"
})

@ToString
public class RootType {

    @XmlElement(required = true)
    protected ControllersType controllers;

    /**
     * Gets the value of the controllers property.
     *
     * @return possible object is
     * {@link ControllersType }
     */
    public ControllersType getControllers() {
        return controllers;
    }

    /**
     * Sets the value of the controllers property.
     *
     * @param value allowed object is
     *              {@link ControllersType }
     */
    public void setControllers(ControllersType value) {
        this.controllers = value;
    }

}
