//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.19 at 12:54:00 AM MSK 
//


package ru.datana.steel.parser.model.xml;

import lombok.Data;

import javax.xml.bind.annotation.*;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "controllerType", propOrder = {
        "value"
})
@Data
public class ControllerType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "ip")
    protected String ip;
    @XmlAttribute(name = "rack")
    protected String rack;
    @XmlAttribute(name = "slot")
    protected String slot;
    @XmlAttribute(name = "note")
    protected String note;

//    /**
//     * Гистерезис в обсалютных значенияих или в процентах
//     */
//    @XmlAttribute(name = "abs")
//    private Boolean abs;
//
//    /**
//     * Гистерезис
//     */
//    @XmlAttribute(name = "husteresis")
//    private String husteresis;
//
//    /**
//     * Записывать значение в runtime таблицу
//     */
//    @XmlAttribute(name = "rt")
//    private Boolean rt;
//

}
